# Generated by Django 4.1 on 2023-08-17 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Orario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariffa', models.DecimalField(decimal_places=1, max_digits=8)),
                ('ore', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Pezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=1, max_digits=8)),
                ('numero', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Societa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sottocampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('content_id', models.PositiveIntegerField()),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_slug', models.SlugField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modifica', models.DateTimeField(auto_now=True)),
                ('societa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='visual.societa')),
            ],
        ),
        migrations.CreateModel(
            name='CampoSottocampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=1)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.campo')),
                ('sottocampo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.sottocampo')),
            ],
        ),
        migrations.AddField(
            model_name='campo',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campi', to='visual.prodotto'),
        ),
        migrations.AddField(
            model_name='campo',
            name='sottocampi',
            field=models.ManyToManyField(related_name='sottocampi', through='visual.CampoSottocampo', to='visual.sottocampo'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('cognome', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('societa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti', to='visual.societa')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
