# Generated by Django 4.1 on 2023-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_alter_sottocampo_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='sottocampi',
            field=models.ManyToManyField(related_name='prodotto', to='visual.sottocampo'),
        ),
        migrations.AddField(
            model_name='societa',
            name='sottocampoi',
            field=models.ManyToManyField(related_name='societa', to='visual.sottocampo'),
        ),
    ]
