# Generated by Django 4.1 on 2023-08-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('visual', '0003_prodotto_sottocampi_societa_sottocampoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocampo',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
