# Generated by Django 4.1 on 2023-08-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_alter_sottocampo_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='societa',
            old_name='sottocampoi',
            new_name='sottocampi',
        ),
    ]
