# Generated by Django 4.1 on 2023-09-04 16:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_rename_sottocampoi_societa_sottocampi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orario',
            name='tariffa',
            field=models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='pezzo',
            name='costo',
            field=models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
